version: '3.8'

services:
  snomed-db:
    image: postgres:15-alpine
    container_name: snomed_irbd_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-snomed_password}
      POSTGRES_DB: ${DB_NAME:-snomed_irbd}
    volumes:
      - snomed_data:/var/lib/postgresql/data
      - ./data/init_db:/docker-entrypoint-initdb.d

volumes:
  snomed_data: